DROP DATABASE IF EXISTS BAMAZON_DB;

CREATE DATABASE BAMAZON_DB;

USE BAMAZON_DB;

CREATE TABLE DEPARTMENT(
	DEPT_ID INT NOT NULL AUTO_INCREMENT,
    DEPT_NAME VARCHAR(25) NOT NULL, 
    PRIMARY KEY(DEPT_ID)
    );

CREATE TABLE PRODUCTS(
    ITEM_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DEPT_ID INT NOT NULL,
    PRICE DECIMAL(6, 2),
    STOCK_QUANTITY INTEGER,
    PRIMARY KEY(ITEM_ID)
);


    ALTER TABLE PRODUCTS
	ADD FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID); 

    INSERT INTO DEPARTMENT (DEPT_NAME)
    VALUES ('PETS');
    
    INSERT INTO DEPARTMENT (DEPT_NAME)
    VALUES ('HARDWARE');
    
    INSERT INTO DEPARTMENT (DEPT_NAME)
    VALUES ('KITCHEN'), ('BATH'), ('ELECTRONICS'), ('OFFICE'), ('GARDEN');
    
    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("PUPPY PAWS STROLLER", 1, 39.99, 3);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("2IN. ANGLED PAINTBRUSH", 2, 8.99, 10);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("10IN. SKILLET", 3, 29.99, 4);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("PLUSH BATH TOWEL, LG", 4, 9.99, 25);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("BAMAZON ALEXA, 3IN. BT", 5, 49.99, 17);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("70 PAGE SPIRAL/BOUND NOTEBOOK/COUNT 10", 6, 1.78, 46);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("BANANA jPHONE V.8", 5, 899.99, 12);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("KITCHENWORKS 12C. COFFEEMAKER", 3, 69.99, 9);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("10 PIECE SCREWDRIVER SET", 2, 19.99, 127);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("SQUIRREL FOOD, PEANUT MIXTURE", 7, 8.69, 77);