DROP DATABASE IF EXISTS BAMAZON_DB;

CREATE DATABASE BAMAZON_DB;

USE BAMAZON_DB;

CREATE TABLE PRODUCTS
(
    ITEM_ID INT(10) NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50),
    DEPARTMENT_NAME VARCHAR(30),
    PRICE DECIMAL(6, 2),
    STOCK_QUANTITY INTEGER(10),
    PRIMARY KEY(ITEM_ID)
);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("PUPPY PAWS STROLLER", "PETS", 39.99, 3);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("2IN. ANGLED PAINTBRUSH", "HARDWARE DEPT", 8.99, 10);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("10IN. SKILLET", "KITCHEN", 29.99, 4);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("PLUSH BATH TOWEL, LG", "BATH", 9.99, 25);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("BAMAZON ALEXA, 3IN. BT", "ELECTRONICS", 49.99, 17);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("70 PAGE SPIRAL/BOUND NOTEBOOK/COUNT 10", "OFFICE", 1.78, 46);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("BANANA jPHONE V.8", "ELECTRONICS", 899.99, 12);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("KITCHENWORKS 12C. COFFEEMAKER", "KITCHEN", 69.99, 9);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("10 PIECE SCREWDRIVER SET", "HARDWARE", 19.99, 127);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPARTMENT_NAME,PRICE,STOCK_QUANTITY)
    VALUES("SQUIRREL FOOD, PEANUT MIXTURE", "GARDEN", 8.69, 77);